export enum ENUM_USER_STATUS_CODE_ERROR {
    USER_NOT_FOUND_ERROR = 5200,
    USER_EMAIL_EXIST_ERROR = 5201,
    USER_PASSWORD_NOT_MATCH_ERROR = 5202,
    USER_PASSWORD_EXPIRED_ERROR = 5203,
    USER_PASSWORD_ATTEMPT_MAX_ERROR = 5204,
    USER_BLOCKED_ERROR = 5205,
}

export enum ENUM_USER_STATUS_CODE_SUCCESS {
    USER_PASSWORD_EXPIRED_ERROR = 1000,
}
